apiVersion: v1
kind: Secret
metadata:
  name: somleng-secrets
  namespace: somleng
type: Opaque
stringData:
  # CHANGE ALL OF THESE before deploying
  POSTGRES_PASSWORD: "CHANGE_ME"
  SECRET_KEY_BASE: "CHANGE_ME"
  FS_ESL_PASSWORD: "CHANGE_ME"
  ANYCABLE_SECRET: "CHANGE_ME"
  RATING_ENGINE_PASSWORD: "CHANGE_ME"
